### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by anotherfinemess84** [cpz/EfiLoader#1]
Hi, can I ask a question about this?  I know the repo is empty but im interested in this.  Thanks

**Comment by cpz** [comment]
Hello,
Yeah, sure. 
Atm repo is emty but almost finished project.

**Comment by anotherfinemess84** [comment]
Is it based off MattiWatti's EFI Guard?
https://github.com/Mattiwatti/EfiGuard

Do you have Skype or Discord?

Thanks,

**Comment by cpz** [comment]
Hello!
You totally right, it based of Efi Guard.

Please, message me your email and then I'll send email with mine discord on it.

**Comment by anotherfinemess84** [comment]
anotherfinemess84@gmail.com

Thank you
